-- Schéma relationnel de données
-- Base de données <Cheschire>
-- Author : hacknonym
-- bd_name : Cheschire

-- mysql> CREATE DATABASE Cheschire;
-- $> mysql -u $MYSQL_USER -p $MYSQL_PASS Cheschire < mydb.sql
-- mysql> SOURCE /root/mydb.sql


-- -----------------------------
-- Table structure for `Country` 
-- -----------------------------
--DROP TABLE IF EXISTS `Country`;
CREATE TABLE `Country` 
(
	`Id_Country` VARCHAR(2) NOT NULL,
	`Name` VARCHAR(60) NOT NULL,
	PRIMARY KEY (`Id_Country`)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

--MariaDB [Cheschire]> DESCRIBE Country;
--+------------+-------------+------+-----+---------+-------+
--| Field      | Type        | Null | Key | Default | Extra |
--+------------+-------------+------+-----+---------+-------+
--| Id_Country | varchar(2)  | NO   | PRI | NULL    |       |
--| Name       | varchar(60) | NO   |     | NULL    |       |
--+------------+-------------+------+-----+---------+-------+


-- ----------------------------
-- Table structure for `Victim`
-- ----------------------------
--DROP TABLE IF EXISTS `Victim`;
CREATE TABLE `Victim`
(
	`Id_Victim` INT NOT NULL AUTO_INCREMENT,
	`Date_Compromise` DATETIME,
	`IP_Address` VARCHAR(15),
	`ISP` TEXT,
	`Country` VARCHAR(2),
	`Region` TEXT,
	`City` TEXT,
	`Timezone` VARCHAR(100),
	`User_Name` VARCHAR(50),
	`Computer_Name` VARCHAR(50),
	`Ident` VARCHAR(17),
	`Secret_Key` VARCHAR(45),
	PRIMARY KEY (`Id_Victim`),
	FOREIGN KEY (`Country`) REFERENCES Country (`Id_Country`)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

--MariaDB [Cheschire]> DESCRIBE Victim;
--+-----------------+--------------+------+-----+---------+----------------+
--| Field           | Type         | Null | Key | Default | Extra          |
--+-----------------+--------------+------+-----+---------+----------------+
--| Id_Victim       | int(11)      | NO   | PRI | NULL    | auto_increment |
--| Date_Compromise | datetime     | YES  |     | NULL    |                |
--| IP_Address      | varchar(15)  | YES  |     | NULL    |                |
--| ISP             | text         | YES  |     | NULL    |                |
--| Country         | varchar(2)   | YES  | MUL | NULL    |                |
--| Region          | text         | YES  |     | NULL    |                |
--| City            | text         | YES  |     | NULL    |                |
--| Timezone        | varchar(100) | YES  |     | NULL    |                |
--| User_Name       | varchar(50)  | YES  |     | NULL    |                |
--| Computer_Name   | varchar(50)  | YES  |     | NULL    |                |
--| Ident           | varchar(17)  | YES  |     | NULL    |                |
--| Secret_Key      | varchar(45)  | YES  |     | NULL    |                |
--+-----------------+--------------+------+-----+---------+----------------+


--TABLE (Country)
--https://laendercode.net/fr/2-letter-list.html
INSERT INTO Country (Id_Country, Name)
VALUES
('AF', 'Afghanistan'),
('AX', 'Îles Aland'),
('AL', 'Albanie'),
('DZ', 'Algérie'),
('AS', 'Samoa américaines'),
('AD', 'Andorre'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctique'),
('AG', 'Antigua-et-Barbuda'),
('AR', 'Argentine'),
('AM', 'Arménie'),
('AW', 'Aruba'),
('AU', 'Australie'),
('AT', 'Autriche'),
('AZ', 'Azerbaïdjan'),
('BS', 'Bahamas'),
('BH', 'Bahreïn'),
('BD', 'Bangladesh'),
('BB', 'Barbades'),
('BY', 'Biélorussie'),
('BE', 'Belgique'),
('BZ', 'Belize'),
('BJ', 'Bénin'),
('BM', 'Bermudes'),
('BT', 'Bhoutan'),
('BO', 'Bolivie'),
('BQ', 'Saba, Saint-Eustache et Bonaire'),
('BA', 'Bosnie-Herzégovine'),
('BW', 'Botswana'),
('BV', 'Île Bouvet'),
('BR', 'Brésil'),
('IO', 'Territoire Britannique de l Océan Indien'),
('VG', 'Îles Vierges britanniques'),
('BN', 'Brunei'),
('BG', 'Bulgarie'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodge'),
('CM', 'Cameroun'),
('CA', 'Canada'),
('CV', 'Cap vert'),
('KY', 'Îles Caïmans'),
('CF', 'République centrafricaine'),
('TD', 'Tchad'),
('CL', 'Chili'),
('CN', 'Chine'),
('CX', 'Îles Christmas'),
('CC', 'Îles Cocos'),
('CO', 'Colombie'),
('KM', 'Comores'),
('CK', 'Îles Cook'),
('CR', 'Costa Rica'),
('HR', 'Croatie'),
('CU', 'Cuba'),
('CW', 'Curaçao'),
('CY', 'Chypre'),
('CZ', 'République Tchèque'),
('CD', 'République démocratique du Congo'),
('DK', 'Danemark'),
('DJ', 'Djibouti'),
('DM', 'Dominique'),
('DO', 'République Dominicaine'),
('TL', 'Timor oriental'),
('EC', 'Équateur'),
('EG', 'Égypte'),
('SV', 'Le Salvador'),
('GQ', 'Guinée équatoriale'),
('ER', 'Érythrée'),
('EE', 'Estonie'),
('ET', 'Éthiopie'),
('FK', 'Îles Falkland'),
('FO', 'Îles Féroé'),
('FJ', 'Fiji'),
('FI', 'Finlande'),
('FR', 'France'),
('GF', 'Guyane française'),
('PF', 'Polynésie française'),
('TF', 'Terres australes et antarctiques françaises'),
('GA', 'Gabon'),
('GM', 'Gambie'),
('GE', 'État de Géorgie'),
('DE', 'Allemagne'),
('GH', 'Ghana'),
('GI', 'Gribraltar'),
('GR', 'Grèce'),
('GL', 'Groenland'),
('GD', 'Grenade'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatémala'),
('GG', 'Guernesey'),
('GN', 'Guinée'),
('GW', 'Guinée-Bissau'),
('GY', 'Guyane'),
('HT', 'Haïti'),
('HM', 'Îles Heard et îles MacDonald'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hongrie'),
('IS', 'Islande'),
('IN', 'Inde'),
('ID', 'Indonésie'),
('IR', 'Iran'),
('IQ', 'Irak'),
('IE', 'Irlande'),
('IM', 'Île de Man'),
('IL', 'Israël'),
('IT', 'Italie'),
('CI', 'Côte-d Ivoire'),
('JM', 'Jamaïque'),
('JP', 'Japon'),
('JE', 'Jersey'),
('JO', 'Jordanie'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('XK', 'Kosovo'),
('KW', 'Koweït'),
('KG', 'Kirghizistan'),
('LA', 'Laos'),
('LV', 'Lettonie'),
('LB', 'Liban'),
('LS', 'Lesotho'),
('LR', 'Libéria'),
('LY', 'Libye'),
('LI', 'Liechtenstein'),
('LT', 'Lituanie'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macédoine'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysie'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malte'),
('MH', 'Îles Marshall'),
('MQ', 'Martinique'),
('MR', 'Mauritanie'),
('MU', 'Île Maurice'),
('YT', 'Mayotte'),
('MX', 'Mexique'),
('FM', 'Micronésie'),
('MD', 'Moldavie'),
('MC', 'Monaco'),
('MN', 'Mongolie'),
('ME', 'Monténégro'),
('MS', 'Montserrat'),
('MA', 'Maroc'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibie'),
('NR', 'Nauru'),
('NP', 'Népal'),
('NL', 'Pays-Bas'),
('AN', 'Antilles néerlandaises'),
('NC', 'Nouvelle-Calédonie'),
('NZ', 'Nouvelle Zélande'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigéria'),
('NU', 'Niue'),
('NF', 'Île Norfolk'),
('KP', 'Corée du Nord'),
('MP', 'Îles Mariannes du Nord'),
('NO', 'Norvège'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palaos'),
('PS', 'Territoire Palestinien'),
('PA', 'Panama'),
('PG', 'Papouasie-Nouvelle-Guinée'),
('PY', 'Paraguay'),
('PE', 'Pérou'),
('PH', 'Philippines'),
('PN', 'Îles Pitcairn'),
('PL', 'Pologne'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('CG', 'République du Congo'),
('RE', 'La Réunion'),
('RO', 'Roumanie'),
('RU', 'Russie'),
('RW', 'Rwanda'),
('BL', 'Saint Barthélemy'),
('SH', 'Sainte-Hélène'),
('KN', 'Saint-Kitts-et-Nevis'),
('LC', 'Sainte-Lucie'),
('MF', 'Saint-Martin'),
('PM', 'Saint Pierre et Miquelon'),
('VC', 'Saint-Vincent-et-les-Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marin'),
('ST', 'Sao Tomé-et-Principe'),
('SA', 'Arabie Saoudite'),
('SN', 'Sénégal'),
('RS', 'Serbie'),
('CS', 'Serbie et Montenegro'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapour'),
('SX', 'Saint-Martin'),
('SK', 'Slovaquie'),
('SI', 'Slovénie'),
('SB', 'Îles Salomon'),
('SO', 'Somalie'),
('ZA', 'Afrique du Sud'),
('GS', 'Géorgie du Sud et les îles Sandwich'),
('KR', 'Corée du Sud'),
('SS', 'Soudan du Sud'),
('ES', 'Espagne'),
('LK', 'Sri Lanka'),
('SD', 'Soudan'),
('SR', 'Surinam'),
('SJ', 'Svalbard et Jan Mayen'),
('SZ', 'Swaziland'),
('SE', 'Suède'),
('CH', 'Suisse'),
('SY', 'Syrie'),
('TW', 'Taiwan'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzanie'),
('TH', 'Thaïlande'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinité et Tobago'),
('TN', 'Tunisie'),
('TR', 'Turquie'),
('TM', 'Turkménistan'),
('TC', 'Îles Turques et Caïques'),
('TV', 'Tuvalu'),
('VI', 'Îles Vierges des États-Unis'),
('UG', 'Ouganda'),
('UA', 'Ukraine'),
('AE', 'Émirats Arabes Unis'),
('GB', 'Royaume-Uni'),
('US', 'États-Unis (USA)'),
('UM', 'Îles Mineures éloignées des États-Unis'),
('UY', 'Uruguay'),
('UZ', 'Ouzbékistan'),
('VU', 'Vanuatu'),
('VA', 'Vatican'),
('VE', 'Vénézuela'),
('VN', 'Vietnam'),
('WF', 'Wallis et Futuna'),
('EH', 'Sahara occidental'),
('YE', 'Yemen'),
('ZM', 'Zambie'),
('ZW', 'Zimbabwe');
